### PR TITLE
CI/travis: use libiio's lib.sh logic for building the repo

### PR DESCRIPTION
**Pull request by commodo**
After a bit of effort, here are some initial results of a pipeline.

https://travis-ci.org/analogdevicesinc/libad9361-iio/builds/470445438

There is still something to fix in libiio, with respect to generating good RPMs for CentOS 7 ; that's CentOS' fault and we have a workaround/hack for that ; we've reported it with them, and provided the fix [a while back].

Fixing/hacking libiio's build will take place in parallel with this PR.
But I wanted to give this a bit of a preview of this, before that's being done.
It is a bit frustrating that to fix stuff in a pipeline, especially when it's in parts before a certain step, because testing also means having to re-propagate things a few times.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>

### CODE REVIEW

**Comment by tfcollins** [comment]
What is the extent that we enable pipelined builds? I mean do this only happen with master or PRs to master, or all libiio branch pushes? All branches I think it a bit overkill.

**Comment by commodo** [comment]
Pipelines trigger only for master and release branches (e.g. 2018_R1 and friends)
Other branches just build, but don’t propagate.

This triggers only for pushes, and not PRs

**Comment by commodo** [comment]
Will merge tomorrow after PR https://github.com/analogdevicesinc/libiio/pull/250 is merged

**Comment by commodo** [comment]
closing & re-opening to trigger build

**Pull request merged**
