### PR TITLE
travis-ci : build and deploy Linux and OSX packages

### PR DESCRIPTION
**Pull request by rgetz**
many parts borrowed from libiio travis files

Signed-off-by: Robin Getz <robin.getz@analog.com>

### CODE REVIEW

**Comment by tfcollins** [comment]
Will this constantly overwrite the built versions like libiio does for the different OS versions?

**Comment by rgetz** [comment]
yes - unfortunately we pay for storage on swdownloads.analog.com, and don't have unlimited storage. It keeps the last 10 builds from every branch.

**Comment by rgetz** [comment]
For the releases? Yes - the same bug is here as well. I didn't think about fixing it yet.

**Comment by tfcollins** [comment]
Yes the release was the one I was curious about.  I'll update the issues.

**Comment by mhennerich** [comment]
Assigned #6 to me - what do you want me to do?

**Pull request merged**
